### ISSUE TITLE
docker restart of container does not gracefully stop the server

### ISSUE THREAD

**Issue by codegain** [Hermsi1337/docker-ark-server#38]
Hi,

I had the following issue: Some of my friends were playing on the server and after like 10 minutes I tested to restart the server using `docker restart ark_server` (I installed the server using the `docker run` command).
This somehow doesn't trigger a "graceful stop" of the server, because all items in the inventory of my friends were lost.

ARK-Server-Tools state that stopping/restarting the server gracefully would result in a worldsave. Manually saving the world via `docker exec ark_server arkmanager worldsave` and restarting via `docker restart ark_server` did indeed save the world.

Are there any options for `docker restart` or the `docker run` command which need to be added in order that `docker restart` causes a graceful stop? Or can this somehow be added to the docker image to save the world in case the container restarts (server reboot/manual restart)?

**Comment by Hermsi1337** [comment]
Hey @codegain I've released a new version of the image. Could you try with current `latest` ?

**Comment by Mickroz** [comment]
I experienced the same today, the docker container got updated by watchtower and my brother lost everything he build.

**Comment by YaibaToKen** [comment]
I'l like to point out that as of today, this situation still happens.
